<?php

namespace App\Filament\Resources\SeriesResource\Pages;

use App\Filament\Resources\SeriesResource;
use App\Models\Episode;
use Filament\Actions;
use Filament\Forms\Components\TextInput;
use Filament\Forms\Form;
use Filament\Resources\Pages\CreateRecord;
use Illuminate\Database\Eloquent\Model;

class CreateSeriesEpisodePage extends CreateRecord
{
    protected static string $resource = SeriesResource::class;

    public function mount(): void
    {
        dd(request('season'));
        parent::mount();

        $this->record = request('season');

    }

    public function getModel(): string
    {
        return Episode::class; // TODO: Change the autogenerated stub
    }

    protected function getFormModel(): Model|string|null
    {
        return $this->getModel();
    }


    public function form(Form $form): Form
    {
        return $form->schema([
            TextInput::make('title')
        ]);
    }
}
